from pydantic import BaseModel
from datetime import datetime
from enum import Enum, IntEnum

class Tick(BaseModel):
    datetime: datetime
    bid: float
    ask: float
    last: float
    volume: int
    time_msc: int
    flags: int
    volume_real: float

class Rates(BaseModel):
    time: datetime
    open: float
    high: float
    low: float
    close: float
    tick_volume: int
    spread: int
    real_volume: int

class ENUM_TRADE_TRANSACTION_TYPE(str, Enum):
    TRADE_TRANSACTION_ORDER_ADD = "TRADE_TRANSACTION_ORDER_ADD"
    TRADE_TRANSACTION_ORDER_UPDATE = "TRADE_TRANSACTION_ORDER_UPDATE"
    TRADE_TRANSACTION_ORDER_DELETE = "TRADE_TRANSACTION_ORDER_DELETE"
    TRADE_TRANSACTION_DEAL_ADD = "TRADE_TRANSACTION_DEAL_ADD"
    TRADE_TRANSACTION_DEAL_UPDATE = "TRADE_TRANSACTION_DEAL_UPDATE"
    TRADE_TRANSACTION_DEAL_DELETE = "TRADE_TRANSACTION_DEAL_DELETE"
    TRADE_TRANSACTION_HISTORY_ADD = "TRADE_TRANSACTION_HISTORY_ADD"
    TRADE_TRANSACTION_HISTORY_UPDATE = "TRADE_TRANSACTION_HISTORY_UPDATE"
    TRADE_TRANSACTION_HISTORY_DELETE = "TRADE_TRANSACTION_HISTORY_DELETE"
    TRADE_TRANSACTION_POSITION = "TRADE_TRANSACTION_POSITION"
    TRADE_TRANSACTION_REQUEST = "TRADE_TRANSACTION_REQUEST"

class ENUM_ORDER_TYPE(int, Enum):
    ORDER_TYPE_BUY = 0
    ORDER_TYPE_SELL = 1
    ORDER_TYPE_BUY_LIMIT = 2
    ORDER_TYPE_SELL_LIMIT = 3
    ORDER_TYPE_BUY_STOP = 4
    ORDER_TYPE_SELL_STOP = 5

class ENUM_ORDER_STATE(str, Enum):
    ORDER_STATE_STARTED = "ORDER_STATE_STARTED"
    ORDER_STATE_PLACED = "ORDER_STATE_PLACED"
    ORDER_STATE_CANCELED = "ORDER_STATE_CANCELED"
    ORDER_STATE_PARTIAL = "ORDER_STATE_PARTIAL"
    ORDER_STATE_FILLED = "ORDER_STATE_FILLED"
    ORDER_STATE_REJECTED = "ORDER_STATE_REJECTED"
    ORDER_STATE_EXPIRED = "ORDER_STATE_EXPIRED"
    ORDER_STATE_REQUEST_ADD = "ORDER_STATE_REQUEST_ADD"
    ORDER_STATE_REQUEST_MODIFY = "ORDER_STATE_REQUEST_MODIFY"
    ORDER_STATE_REQUEST_CANCEL = "ORDER_STATE_REQUEST_CANCEL"

class ENUM_DEAL_TYPE(str, Enum):
    DEAL_TYPE_BUY = "DEAL_TYPE_BUY"
    DEAL_TYPE_SELL = "DEAL_TYPE_SELL"
    DEAL_TYPE_BALANCE = "DEAL_TYPE_BALANCE"
    DEAL_TYPE_CREDIT = "DEAL_TYPE_CREDIT"
    DEAL_TYPE_CHARGE = "DEAL_TYPE_CHARGE"
    DEAL_TYPE_CORRECTION = "DEAL_TYPE_CORRECTION"
    DEAL_TYPE_BONUS = "DEAL_TYPE_BONUS"
    DEAL_TYPE_COMMISSION = "DEAL_TYPE_COMMISSION"
    DEAL_TYPE_COMMISSION_DAILY = "DEAL_TYPE_COMMISSION_DAILY"
    DEAL_TYPE_COMMISSION_MONTHLY = "DEAL_TYPE_COMMISSION_MONTHLY"
    DEAL_TYPE_COMMISSION_AGENT_DAILY = "DEAL_TYPE_COMMISSION_AGENT_DAILY"
    DEAL_TYPE_COMMISSION_AGENT_MONTHLY = "DEAL_TYPE_COMMISSION_AGENT_MONTHLY"
    DEAL_TYPE_INTEREST = "DEAL_TYPE_INTEREST"
    DEAL_TYPE_BUY_CANCELED = "DEAL_TYPE_BUY_CANCELED"
    DEAL_TYPE_SELL_CANCELED = "DEAL_TYPE_SELL_CANCELED"
    DEAL_DIVIDEND = "DEAL_DIVIDEND"
    DEAL_DIVIDEND_FRANKED = "DEAL_DIVIDEND_FRANKED"
    DEAL_TAX = "DEAL_TAX"

class ENUM_ORDER_TYPE_TIME(str, Enum):
    ORDER_TIME_GTC = "ORDER_TIME_GTC"
    ORDER_TIME_DAY = "ORDER_TIME_DAY"
    ORDER_TIME_SPECIFIED = "ORDER_TIME_SPECIFIED"
    ORDER_TIME_SPECIFIED_DAY = "ORDER_TIME_SPECIFIED_DAY"

class ENUM_TRADE_REQUEST_ACTIONS(str, Enum):
    TRADE_ACTION_DEAL="TRADE_ACTION_DEAL"
    TRADE_ACTION_PENDING="TRADE_ACTION_PENDING"
    TRADE_ACTION_SLTP="TRADE_ACTION_SLTP"
    TRADE_ACTION_MODIFY="TRADE_ACTION_MODIFY"
    TRADE_ACTION_REMOVE="TRADE_ACTION_REMOVE"
    TRADE_ACTION_CLOSE_BY="TRADE_ACTION_CLOSE_BY"

class ENUM_ORDER_TYPE_FILLING(str, Enum):
    ORDER_FILLING_FOK="ORDER_FILLING_FOK"
    ORDER_FILLING_IOC="ORDER_FILLING_IOC"
    ORDER_FILLING_RETURN="ORDER_FILLING_RETURN"

class ENUM_TIMEFRAME(str, Enum):
    PERIOD_CURRENT=0
    PERIOD_M1=1
    PERIOD_M5=5
    PERIOD_M15=15
    PERIOD_M30=30
    PERIOD_H1=60
    PERIOD_H4=240
    PERIOD_D1=1440
    PERIOD_W1=10080
    PERIOD_MN1=43200
